Este es un ejercicio divertido que en **Python**, que con la ayuda de **Pandas**, se puede resolver sin problemas.
Se trata de obtener datos interesantes del dataset de las Bundesliga

In [1]:
# Importamos pandas para el análisis.
import pandas as pd
# #from  itertools import combinations

In [ ]:
# Cargamos el dataset desde un archivo csv.
df = pd.read_csv("data/raw/Bundesliga.csv")

In [2]:
# Imprimimos el head del dataset (los primeros 5 registros)
print("df.head:")
df.head()

df.head:

,Unnamed: 0,HomeTeam,AwayTeam,HomeGoals,AwayGoals,Round,Year,Date
0,1,Werder Bremen,Borussia Dortmund,3,2,1,1963,1963-08-24 09:30:00
1,2,Hertha BSC Berlin,1. FC Nuernberg,1,1,1,1963,1963-08-24 09:30:00
2,3,Preussen Muenster,Hamburger SV,1,1,1,1963,1963-08-24 09:30:00
3,4,Eintracht Frankfurt,1. FC Kaiserslautern,1,1,1,1963,1963-08-24 09:30:00
4,5,Karlsruher SC,Meidericher SV,1,4,1,1963,1963-08-24 09:30:00

In [3]:
print("df.dtypes:")
df.dtypes

df.dtypes:

Unnamed: 0     int64
HomeTeam      object
AwayTeam      object
HomeGoals      int64
AwayGoals      int64
Round          int64
Year           int64
Date          object
dtype: object

In [4]:
print("df.info:")
df.info

df.info:

<bound method DataFrame.info of        Unnamed: 0                   HomeTeam              AwayTeam  HomeGoals  \
0               1              Werder Bremen     Borussia Dortmund          3
1               2          Hertha BSC Berlin       1. FC Nuernberg          1
2               3          Preussen Muenster          Hamburger SV          1
3               4        Eintracht Frankfurt  1. FC Kaiserslautern          1
4               5              Karlsruher SC        Meidericher SV          1
...           ...                        ...                   ...        ...
14013       14014          Arminia Bielefeld           Hannover 96          2
14014       14015              Karlsruher SC     Hertha BSC Berlin          4
14015       14016                1. FC Koeln            VfL Bochum          1
14016       14017  Borussia Moenchengladbach     Borussia Dortmund          1
14017       14018                 Schalke 04       1899 Hoffenheim          2

       AwayGoals  Round  Year                 Date
0              2      1  1963  1963-08-24 09:30:00
1              1      1  1963  1963-08-24 09:30:00
2              1      1  1963  1963-08-24 09:30:00
3              1      1  1963  1963-08-24 09:30:00
4              4      1  1963  1963-08-24 09:30:00
...          ...    ...   ...                  ...
14013          2     34  2008  2009-05-23 08:30:00
14014          0     34  2008  2009-05-23 08:30:00
14015          1     34  2008  2009-05-23 08:30:00
14016          1     34  2008  2009-05-23 08:30:00
14017          3     34  2008  2009-05-23 08:30:00

[14018 rows x 8 columns]>

In [5]:
print("df.coluns:")
df.columns

df.coluns:

Index(['Unnamed: 0', 'HomeTeam', 'AwayTeam', 'HomeGoals', 'AwayGoals', 'Round',
       'Year', 'Date'],
      dtype='object')

In [6]:
# Dos maneras diferentes de establecer los nombres de las columnas
# 1. Para todas las columnas
schema = ['index', 'homeTeam', 'awayTeam', 'homeGoals', 'awayGoals', 'round', 'year', 'date']
df.columns = schema
# 2. Sólo para las columnas seleccionadas
#df.rename(columns = {'Unnamed: 0': 'Index'}, inplace = True)
print("df.coluns:")
df.columns

df.coluns:

Index(['index', 'homeTeam', 'awayTeam', 'homeGoals', 'awayGoals', 'round',
       'year', 'date'],
      dtype='object')

In [ ]:
pd.to_datetime(df.date).dt.strftime("%Y-%M-%d $H:$M:$S")
print(df.head())

In [9]:
print("Count:")
df.count()

Count:

index        14018
homeTeam     14018
awayTeam     14018
homeGoals    14018
awayGoals    14018
round        14018
year         14018
date         14016
dtype: int64

In [97]:
print("Filter by homeTeam and awayTeam that's contains: 'Freiburg'")
# freiburg = df[df['HomeTeam'].str.contains('Freiburg')]
df.loc[df['homeTeam'].str.contains('Freiburg') | df['awayTeam'].str.contains('Freiburg')].head()

Filter by homeTeam and awayTeam that's contains: 'Freiburg'

,index,homeTeam,awayTeam,homeGoals,awayGoals,round,year,date
9127,9128,Bayern Muenchen,SC Freiburg,3,1,1,1993,1993-08-07 08:30:00
9134,9135,SC Freiburg,Wattenscheid 09,4,1,2,1993,1993-08-14 08:30:00
9146,9147,Borussia Dortmund,SC Freiburg,3,2,3,1993,1993-08-21 08:30:00
9149,9150,SC Freiburg,Hamburger SV,0,1,4,1993,1993-08-27 12:30:00
9163,9164,1. FC Koeln,SC Freiburg,2,0,5,1993,1993-09-01 12:30:00

In [11]:
print("Filter: homeGoals >= 10")
df.loc[df['homeGoals'] >= 10]

Filter: homeGoals >= 10

,index,homeTeam,awayTeam,homeGoals,awayGoals,round,year,date
943,944,Borussia Moenchengladbach,Schalke 04,11,0,18,1966,1967-01-07 08:30:00
1197,1198,Borussia Moenchengladbach,Borussia Neunkirchen,10,0,12,1967,1967-11-04 08:30:00
2455,2456,Bayern Muenchen,Borussia Dortmund,11,1,16,1971,1971-11-27 08:30:00
4456,4457,Borussia Moenchengladbach,Borussia Dortmund,12,0,34,1977,1978-04-29 08:30:00
5787,5788,Borussia Dortmund,Arminia Bielefeld,11,1,12,1982,1982-11-06 08:30:00
6363,6364,Borussia Moenchengladbach,Eintracht Braunschweig,10,0,8,1984,1984-10-11 14:00:00

In [98]:
print("manyGoalsVector: ")
df.loc[df['homeGoals'] >= 10]

manyGoalsVector:

,index,homeTeam,awayTeam,homeGoals,awayGoals,round,year,date
943,944,Borussia Moenchengladbach,Schalke 04,11,0,18,1966,1967-01-07 08:30:00
1197,1198,Borussia Moenchengladbach,Borussia Neunkirchen,10,0,12,1967,1967-11-04 08:30:00
2455,2456,Bayern Muenchen,Borussia Dortmund,11,1,16,1971,1971-11-27 08:30:00
4456,4457,Borussia Moenchengladbach,Borussia Dortmund,12,0,34,1977,1978-04-29 08:30:00
5787,5788,Borussia Dortmund,Arminia Bielefeld,11,1,12,1982,1982-11-06 08:30:00
6363,6364,Borussia Moenchengladbach,Eintracht Braunschweig,10,0,8,1984,1984-10-11 14:00:00

In [13]:
# A DataFrame of a numerical type allows to use functions like min/max/mean.
# This allows to get things like:
print("Min year:")
df['year'].min()

Min year:

1963

In [14]:
print("Max date:")
df['year'].max()

Max date:

2008

In [15]:
print("Average home goals:")
df['homeGoals'].mean()

Average home goals:

1.8981309744614068

In [16]:
print("Average away oals:")
df['awayGoals'].mean()

Average away oals:

1.1907547439006991

In [76]:
print("maxDiff:")
abs(df['homeGoals'].max() - df['awayGoals'].max())

maxDiff:

3

In [18]:
print("Sort awayGoals: Descending")
df.sort_values(by = ['awayGoals'], ascending = False)

Sort awayGoals: Descending

,index,homeTeam,awayTeam,homeGoals,awayGoals,round,year,date
719,720,Tasmania Berlin,Meidericher SV,0,9,27,1965,1966-03-26 08:30:00
739,740,Borussia Neunkirchen,TSV 1860 Muenchen,1,9,29,1965,1966-04-16 08:30:00
11180,11181,SSV Ulm,Bayer Leverkusen,1,9,25,1999,2000-03-18 08:30:00
10734,10735,Borussia Moenchengladbach,Bayer Leverkusen,2,8,10,1998,1998-10-30 13:00:00
4127,4128,Rot-Weiss Essen,Eintracht Frankfurt,1,8,32,1976,1977-05-07 09:30:00
...,...,...,...,...,...,...,...,...
10146,10147,Borussia Dortmund,Arminia Bielefeld,5,0,12,1996,1996-10-26 08:30:00
6200,6201,Borussia Moenchengladbach,VfB Stuttgart,2,0,24,1983,1984-03-10 08:30:00
10143,10144,VfB Stuttgart,Borussia Moenchengladbach,5,0,12,1996,1996-10-26 08:30:00
10142,10143,Hamburger SV,Karlsruher SC,2,0,12,1996,1996-10-26 08:30:00
8932,8933,Hamburger SV,Bayer Uerdingen,3,0,13,1992,1992-11-14 08:30:00

In [19]:
print("Check the total number of teams:")
print(len(df['homeTeam'].unique()))
df['homeTeam'].unique()

Check the total number of teams:
52

array(['Werder Bremen', 'Hertha BSC Berlin', 'Preussen Muenster',
       'Eintracht Frankfurt', 'Karlsruher SC', '1. FC Saarbruecken',
       'TSV 1860 Muenchen', 'Schalke 04', 'Borussia Dortmund',
       '1. FC Nuernberg', 'Hamburger SV', '1. FC Kaiserslautern',
       'Meidericher SV', '1. FC Koeln', 'Eintracht Braunschweig',
       'VfB Stuttgart', 'Borussia Neunkirchen', 'Hannover 96',
       'Tasmania Berlin', 'Bayern Muenchen', 'Borussia Moenchengladbach',
       'MSV Duisburg', 'Rot-Weiss Essen', 'Fortuna Duesseldorf',
       'Alemannia Aachen', 'Kickers Offenbach', 'Rot-Weiss Oberhausen',
       'Arminia Bielefeld', 'VfL Bochum', 'Wuppertaler SV',
       'Fortuna Koeln', 'Tennis Borussia Berlin', 'Bayer Uerdingen',
       'FC St. Pauli', 'Darmstadt 98', 'Bayer Leverkusen',
       'Waldhof Mannheim', 'FC Homburg', 'Blau-Weiss 90 Berlin',
       'Stuttgarter Kickers', 'Wattenscheid 09', 'Dynamo Dresden',
       'Hansa Rostock', 'VfB Leipzig', 'SC Freiburg', 'KFC Uerdingen',
       'VfL Wolfsburg', 'SSV Ulm', 'SpVgg Unterhaching',
       'Energie Cottbus', '1. FSV Mainz 05', '1899 Hoffenheim'],
      dtype=object)

In [101]:
print("unique from homeTeam and awayTeam")
pd.unique(df[['homeTeam', 'awayTeam']].values.ravel())

unique from homeTeam and awayTeam

array(['Werder Bremen', 'Borussia Dortmund', 'Hertha BSC Berlin',
       '1. FC Nuernberg', 'Preussen Muenster', 'Hamburger SV',
       'Eintracht Frankfurt', '1. FC Kaiserslautern', 'Karlsruher SC',
       'Meidericher SV', '1. FC Saarbruecken', '1. FC Koeln',
       'TSV 1860 Muenchen', 'Eintracht Braunschweig', 'Schalke 04',
       'VfB Stuttgart', 'Borussia Neunkirchen', 'Hannover 96',
       'Tasmania Berlin', 'Borussia Moenchengladbach', 'Bayern Muenchen',
       'Fortuna Duesseldorf', 'MSV Duisburg', 'Rot-Weiss Essen',
       'Alemannia Aachen', 'Kickers Offenbach', 'Rot-Weiss Oberhausen',
       'Arminia Bielefeld', 'VfL Bochum', 'Wuppertaler SV',
       'Fortuna Koeln', 'Tennis Borussia Berlin', 'Bayer Uerdingen',
       'FC St. Pauli', 'Darmstadt 98', 'Bayer Leverkusen',
       'Waldhof Mannheim', 'FC Homburg', 'Blau-Weiss 90 Berlin',
       'Stuttgarter Kickers', 'Wattenscheid 09', 'Dynamo Dresden',
       'Hansa Rostock', 'SC Freiburg', 'VfB Leipzig', 'KFC Uerdingen',
       'VfL Wolfsburg', 'SpVgg Unterhaching', 'SSV Ulm',
       'Energie Cottbus', '1. FSV Mainz 05', '1899 Hoffenheim'],
      dtype=object)

In [75]:
df.groupby(['homeGoals','awayGoals']).size().sort_values(ascending = False).head()

homeGoals  awayGoals
1          1            1632
2          1            1203
1          0            1109
2          0            1092
0          0             914
dtype: int64

In [113]:
# lets look at the 15 most successful home teams
# df.sort_values(by=df.loc[df['homeGoals'] > df['awayGoals']].head(15), ascending = False).to_csv("data/raw/marcador.csv", index = False)
# df.loc[df['homeGoals'] > df['awayGoals']].head(15).to_csv("data/raw/marcador.csv", index = False)
marcador = df.loc[df['homeGoals'] > df['awayGoals']].head(15)
marcador

,index,homeTeam,awayTeam,homeGoals,awayGoals,round,year,date
0,1,Werder Bremen,Borussia Dortmund,3,2,1,1963,1963-08-24 09:30:00
7,8,Schalke 04,VfB Stuttgart,2,0,1,1963,1963-08-24 09:30:00
9,10,1. FC Nuernberg,Werder Bremen,3,0,2,1963,1963-08-31 09:30:00
10,11,Hamburger SV,1. FC Saarbruecken,4,2,2,1963,1963-08-31 09:30:00
12,13,Meidericher SV,Eintracht Frankfurt,3,1,2,1963,1963-08-31 09:30:00
13,14,1. FC Koeln,Karlsruher SC,4,0,2,1963,1963-08-31 09:30:00
14,15,Eintracht Braunschweig,Preussen Muenster,1,0,2,1963,1963-08-31 09:30:00
15,16,VfB Stuttgart,Hertha BSC Berlin,2,0,2,1963,1963-08-31 09:30:00
18,19,Preussen Muenster,Meidericher SV,4,2,3,1963,1963-09-07 09:30:00
23,24,Schalke 04,Borussia Dortmund,3,1,3,1963,1963-09-07 09:30:00
24,25,Borussia Dortmund,1. FC Saarbruecken,2,1,4,1963,1963-09-14 09:30:00
26,27,Hamburger SV,Eintracht Frankfurt,3,0,4,1963,1963-09-14 09:30:00
27,28,1. FC Kaiserslautern,Werder Bremen,3,0,4,1963,1963-09-14 09:30:00
30,31,Eintracht Braunschweig,Karlsruher SC,2,0,4,1963,1963-09-14 09:30:00
34,35,Preussen Muenster,VfB Stuttgart,4,2,5,1963,1963-09-21 09:30:00

In [117]:
marcador.sort_values(by = ['homeGoals', 'awayGoals'], ascending = False).head(15)

,index,homeTeam,awayTeam,homeGoals,awayGoals,round,year,date
10,11,Hamburger SV,1. FC Saarbruecken,4,2,2,1963,1963-08-31 09:30:00
18,19,Preussen Muenster,Meidericher SV,4,2,3,1963,1963-09-07 09:30:00
34,35,Preussen Muenster,VfB Stuttgart,4,2,5,1963,1963-09-21 09:30:00
13,14,1. FC Koeln,Karlsruher SC,4,0,2,1963,1963-08-31 09:30:00
0,1,Werder Bremen,Borussia Dortmund,3,2,1,1963,1963-08-24 09:30:00
12,13,Meidericher SV,Eintracht Frankfurt,3,1,2,1963,1963-08-31 09:30:00
23,24,Schalke 04,Borussia Dortmund,3,1,3,1963,1963-09-07 09:30:00
9,10,1. FC Nuernberg,Werder Bremen,3,0,2,1963,1963-08-31 09:30:00
26,27,Hamburger SV,Eintracht Frankfurt,3,0,4,1963,1963-09-14 09:30:00
27,28,1. FC Kaiserslautern,Werder Bremen,3,0,4,1963,1963-09-14 09:30:00
24,25,Borussia Dortmund,1. FC Saarbruecken,2,1,4,1963,1963-09-14 09:30:00
7,8,Schalke 04,VfB Stuttgart,2,0,1,1963,1963-08-24 09:30:00
15,16,VfB Stuttgart,Hertha BSC Berlin,2,0,2,1963,1963-08-31 09:30:00
30,31,Eintracht Braunschweig,Karlsruher SC,2,0,4,1963,1963-09-14 09:30:00
14,15,Eintracht Braunschweig,Preussen Muenster,1,0,2,1963,1963-08-31 09:30:00

 # lets look at the 15 most successful home teams
  df.filter(record => record.homeGoals > record.awayGoals)
    .map(record => record.projectTo(homeTeam))
    .valueCounts()
    .sort(x => x.count, SortOrder.Descending)
    .map(x => (
      homeTeam: x.key.homeTeam,
      count: x.count
    ))
    .take(15)
    .barPlot(x = homeTeam, y = count)
    .show()

In [143]:
df.groupby(['homeTeam','awayTeam']).size().reset_index().rename(columns={0:'count'}).to_csv("data/raw/enfrentados.csv")